const test = require('node:test');
const assert = require('node:assert/strict');
const A = require('../lib/attribution.js');

const ai = [{ id: 'x', verdict: 'ai-generated', hard: true, strength: 0.9 }];

test('C2PA claim generator attributes to OpenAI (confirmed)', () => {
  const r = A.attributeImage(ai, { c2pa: { claimGenerator: 'ChatGPT', signerNames: ['OpenAI'] } });
  assert.equal(r.id, 'openai');
  assert.equal(r.confidence, 'confirmed');
  assert.ok(r.skews.some((k) => k.area === 'Sycophancy'));
});

test('Stable Diffusion parameters attribute to SD family with checkpoint name', () => {
  const r = A.attributeImage(ai, { pngText: { parameters: 'cat\nSteps: 20, Sampler: Euler a, CFG scale: 7, Seed: 1, Model: juggernautXL_v9, Model hash: abc' } });
  assert.equal(r.id, 'stability');
  assert.match(r.detail, /juggernautXL_v9/);
});

test('ComfyUI workflow names the front-end', () => {
  const r = A.attributeImage(ai, { pngText: { prompt: '{"3":{"class_type":"KSampler"}}' } });
  assert.equal(r.id, 'stability');
  assert.match(r.detail, /ComfyUI/);
});

test('Firefly XMP attributes to Adobe; Photoshop-edited camera photo does not', () => {
  assert.equal(A.attributeImage(ai, { xmp: { creatorTool: 'Adobe Firefly' } }).id, 'adobe');
  assert.equal(A.attributeImage([{ verdict: 'captured', strength: 0.4 }], { exif: { software: 'Adobe Photoshop 25' } }), null);
});

test('caption naming Midjourney is declared; host hint is inferred', () => {
  const declared = A.attributeImage([{ id: 'caption-disclosure', verdict: 'ai-disclosed', label: 'x', detail: 'Illustration generated with Midjourney' }], {});
  assert.equal(declared.id, 'midjourney');
  assert.equal(declared.confidence, 'declared');
  const inferred = A.attributeImage([{ id: 'host', verdict: 'suspected', label: 'Served from Midjourney CDN', detail: 'cdn.midjourney.com' }], {});
  assert.equal(inferred.confidence, 'inferred');
});

test('unidentified generator falls back to generic image skews', () => {
  const r = A.attributeImage([{ id: 'filename', verdict: 'suspected', label: 'x', detail: 'ai-generated-1.png' }], {});
  assert.equal(r.id, null);
  assert.ok(r.skews.some((k) => k.area === 'Representation'));
});

test('text disclosure naming ChatGPT is declared; citation markers are confirmed', () => {
  assert.equal(A.attributeText({ verdict: 'ai-assisted-disclosed', disclosures: [{ context: 'written with the help of ChatGPT' }] }).confidence, 'declared');
  const r = A.attributeText({ verdict: 'ai', page: { signals: [{ id: 'markdown-leak', detail: '1× ChatGPT citation marker' }] } });
  assert.equal(r.id, 'openai');
  assert.equal(r.confidence, 'confirmed');
});

test('DeepSeek disclosure surfaces censorship skew', () => {
  const r = A.attributeText({ verdict: 'ai-disclosed', disclosures: [{ context: 'This summary was generated by DeepSeek' }] });
  assert.equal(r.id, 'deepseek');
  assert.ok(A.skewsFor(r, 'text').some((k) => k.area === 'Censorship'));
  assert.ok(A.skewsFor(r, 'text').some((k) => k.area === 'Accuracy' && k.source === 'generic'));
});

test('style-only text hints are labelled as guesses', () => {
  const r = A.attributeText({ verdict: 'likely-ai', page: { signals: [{ id: 'lexicon', detail: '30 points (delve, tapestry)' }] } });
  assert.equal(r.confidence, 'inferred');
  assert.match(r.name, /style only/);
  assert.equal(A.attributeText({ verdict: 'no-signal' }), null);
});

test('site builder attribution surfaces the underlying model vendor', () => {
  const r = A.attributeSite({ verdict: 'ai-built', builder: { name: 'Lovable', kind: 'ai-builder' } });
  assert.equal(r.id, 'lovable');
  assert.match(r.detail, /Claude/);
  const cp = A.attributeSite({ verdict: 'ai-assisted', signals: [{ id: 'code-comment', detail: 'comment: "generated by GitHub Copilot"' }] });
  assert.equal(cp.id, 'microsoft');
  assert.equal(A.attributeSite({ verdict: 'no-signal' }), null);
});

test('every profile has a matcher, marking note and at least one sourced skew', () => {
  for (const p of A.PROFILES) {
    assert.ok(p.match instanceof RegExp, p.id);
    assert.ok(p.marking, p.id);
    assert.ok(p.skews.length >= 1, p.id);
    for (const k of p.skews) assert.ok(k.area && k.note && k.basis, p.id + ' skew');
  }
});
