const test = require('node:test');
const assert = require('node:assert/strict');
const L = require('../lib/lexicons.js');
const T = require('../lib/text-analyzer.js');
const S = require('../lib/signals.js');

const SAMPLES = {
  de: 'Der Hund und die Katze sind nicht das Problem, aber der Nachbar wird sich auch beschweren, denn eine Lösung ist nicht in Sicht. Das Wetter wird auch nicht besser werden, oder doch? Die Kinder der Familie haben das Haus verlassen und werden nicht zurückkommen.',
  fr: "Les enfants des voisins sont dans une situation compliquée pour cette raison, mais nous pensons que vous avez plus de temps avec leur famille qui est plus grande que la nôtre. Les gens dans cette ville sont plus ouverts que les autres familles.",
  es: 'Los niños de las casas están en una situación complicada por esta razón, pero como todo entre más este problema son parte del asunto que tiene todo el mundo. Las personas de esta ciudad son más abiertas que las otras.',
  nl: 'Het is een van de dingen voor deze mensen met zijn eigen problemen, maar deze worden ook door naar over de zaken die niet zijn opgelost en wordt het beter. De mensen van deze stad zijn ook meer open dan de anderen.',
  it: 'Che cosa non va per questo con una delle cose dei problemi sono come anche questo questa nella degli alla fine della storia. Le persone di questa città sono anche più aperte, ma questa situazione che dura da anni non cambia.',
  pt: 'Que coisa não é para este com uma das coisas dos problemas são como também este esta pela pelo mais no fim da história. As pessoas desta cidade são mais abertas, mas esta situação que dura há anos não muda.',
  pl: 'Nie ma się co dziwić, że jest to oraz który która które tego przez jako może bardzo tylko wszystkie sprawy są trudne. Ludzie z tego miasta są bardziej otwarci, ale ta sytuacja, która trwa od lat, jest trudna dla wszystkich.',
  en: 'The quick brown fox and the lazy dog are of the same family that is with us for the reason which we have been told were true from the start. The people of this town are more open, but this situation which has lasted for years is hard.',
};

test('each supported language is identified from its own prose', () => {
  for (const [code, text] of Object.entries(SAMPLES)) {
    const got = L.detectLanguage(text, null);
    assert.equal(got.code, code, code + ' misread as ' + got.code);
    assert.equal(got.source, 'detected');
  }
});

test('a declared language wins over detection', () => {
  const got = L.detectLanguage(SAMPLES.en, 'de-DE');
  assert.equal(got.code, 'de');
  assert.equal(got.source, 'declared');
});

test('short or ambiguous text yields no guess rather than a wrong one', () => {
  assert.equal(L.detectLanguage('Hallo Welt', null).code, null);
  assert.equal(L.detectLanguage('123 456 789 ... !!!', null).code, null);
});

test('AI-generation disclosures are read in every supported language', () => {
  const cases = [
    ['de', 'Dieser Artikel wurde mit Hilfe von KI erstellt.', 'ai-assisted-disclosed'],
    ['de', 'Dieses Bild wurde von KI erstellt.', 'ai-disclosed'],
    ['de', 'Dieses Bild ist KI-generiert.', 'ai-disclosed'],
    ['fr', "Cet article a été généré par l'intelligence artificielle.", 'ai-disclosed'],
    ['es', 'Este texto fue generado por IA.', 'ai-disclosed'],
    ['nl', 'Dit artikel is gegenereerd door AI.', 'ai-disclosed'],
    ['it', "Questo testo è stato generato dall'intelligenza artificiale.", 'ai-disclosed'],
    ['pt', 'Este texto foi gerado por inteligência artificial.', 'ai-disclosed'],
    ['pl', 'Ten tekst został wygenerowany przez sztuczną inteligencję.', 'ai-disclosed'],
  ];
  for (const [lang, text, want] of cases) {
    assert.equal(T.analyzeText(text, { lang }).verdict, want, lang + ': ' + text);
  }
});

test('human-authorship claims are read in every supported language', () => {
  const cases = [
    ['de', 'Alle Texte werden von Menschen geschrieben, ohne KI.'],
    ['fr', "Tous nos articles sont écrits par des humains, sans IA."],
    ['es', 'Todos nuestros textos están escritos por humanos, sin IA.'],
    ['nl', 'Al onze artikelen zijn door mensen geschreven, zonder AI.'],
    ['it', 'Tutti i nostri testi sono scritti da esseri umani, senza IA.'],
    ['pt', 'Todos os nossos textos são escritos por humanos, sem IA.'],
    ['pl', 'Artykuł napisany przez człowieka, bez użycia sztucznej inteligencji.'],
  ];
  for (const [lang, text] of cases) {
    assert.equal(T.analyzeText(text, { lang }).verdict, 'human-disclosed', lang);
  }
});

test('an English disclosure on a non-English page is still found', () => {
  assert.equal(T.analyzeText('Hinweis: This article was generated by AI.', { lang: 'de' }).verdict, 'ai-disclosed');
  assert.equal(S.findDisclosures('Avis : content generated by AI', { lang: 'fr' }).length, 1);
});

test('the English lexicon is never applied to another language', () => {
  // "diverse", "dynamisch", "innovativ" are German words that must not be
  // scored with English tier-2 entries; plain German prose stays clean.
  const plain = SAMPLES.de + ' ' + SAMPLES.de + ' ' + SAMPLES.de;
  const r = T.analyzeText(plain, { lang: 'de' });
  assert.equal(r.verdict, 'no-signal');
  assert.equal(r.language.lexicon, 'German');
});

test('German LLM-typical prose is picked up by the German lexicon', () => {
  const de = 'In der heutigen schnelllebigen digitalen Welt ist es wichtig zu beachten, dass Unternehmen ganzheitliche Lösungen benötigen. Darüber hinaus spielt eine nahtlose Integration eine entscheidende Rolle. Zudem ist maßgeschneiderte Software unverzichtbar. Zusammenfassend lässt sich sagen, dass bahnbrechende Technologien die Landschaft der Branche revolutionieren werden. Letztendlich ist ein facettenreicher Ansatz nicht nur sinnvoll, sondern auch notwendig.';
  const r = T.analyzeText(de, { lang: 'de' });
  assert.ok(['possible-ai', 'likely-ai'].includes(r.verdict), r.verdict);
  assert.ok(r.signals.some((s) => s.id === 'lexicon'));
  assert.ok(r.score < 0.75, 'stylometry alone never reaches the strongest verdict');
});

test('assistant-style leakage is caught in other languages', () => {
  assert.ok(T.analyzeText('Natürlich! Hier ist ein Artikel über Dachdecker. Dächer sind wichtig.', { lang: 'de' }).signals.some((s) => s.id === 'self-reference'));
  assert.ok(T.analyzeText("Bien sûr ! Voici un article sur les toitures. Les toits comptent.", { lang: 'fr' }).signals.some((s) => s.id === 'self-reference'));
});

test('every language pack is well formed', () => {
  for (const code of Object.keys(L.LANGUAGES)) {
    const p = L.get(code);
    assert.ok(p.name, code);
    assert.ok(p.disclosures.length >= 4, code + ' needs generated/assisted/weak/human patterns');
    assert.ok(p.disclosures.some((d) => d.level === 'generated'), code);
    assert.ok(p.disclosures.some((d) => d.level === 'human'), code);
    assert.ok(p.tier1.length >= 10, code + ' tier1');
    assert.ok(p.tier2.length >= 8, code + ' tier2');
    for (const d of p.disclosures) assert.ok(d.re instanceof RegExp, code);
    assert.ok(p.selfRefStrong instanceof RegExp, code);
  }
});

test('an assistance clause is not upgraded to full generation', () => {
  // "created with the help of AI" trips both patterns over the same words.
  for (const [lang, text] of [['de', 'Dieser Artikel wurde mit Hilfe von KI erstellt.'], ['en', 'This post was created with the help of ChatGPT.']]) {
    assert.equal(T.analyzeText(text, { lang }).verdict, 'ai-assisted-disclosed', lang);
  }
  // Separate clauses do not overlap, so a real generation claim survives.
  const both = T.analyzeText('The images were generated by AI. The copy was AI-assisted.', { lang: 'en' });
  assert.equal(both.verdict, 'ai-disclosed');
});
