const test = require('node:test');
const assert = require('node:assert/strict');
const A = require('../lib/site-analyzer.js');

test('Lovable fingerprint → ai-built', () => {
  const r = A.analyzeSite({ hostname: 'shop.example.com', metas: [], scripts: ['https://cdn.gpteng.co/gptengineer.js'], attrNames: ['class', 'data-lov-id'], comments: [], bodyText: '' });
  assert.equal(r.verdict, 'ai-built');
  assert.equal(r.builder.name, 'Lovable');
  assert.equal(r.disclosed, false);
});

test('v0 host → ai-built', () => {
  const r = A.analyzeSite({ hostname: 'my-app.v0.app', bodyText: '' });
  assert.equal(r.verdict, 'ai-built');
});

test('meta disclosure → ai-disclosed', () => {
  const r = A.analyzeSite({ hostname: 'news.example', metas: [{ name: 'ai-generated', content: 'true' }], bodyText: '' });
  assert.equal(r.verdict, 'ai-disclosed');
  assert.ok(r.signals.some((s) => s.id === 'meta-ai'));
});

test('meta declaring no AI is not a disclosure of AI', () => {
  const r = A.analyzeSite({ hostname: 'news.example', metas: [{ name: 'ai-generated', content: 'false' }], bodyText: '' });
  assert.equal(r.verdict, 'no-signal');
  assert.ok(r.signals.some((s) => s.id === 'meta-human'));
});

test('JSON-LD digitalSourceType → ai-disclosed', () => {
  const r = A.analyzeSite({ hostname: 'x', jsonLd: ['{"@type":"ImageObject","digitalSourceType":"http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia"}'], bodyText: '' });
  assert.equal(r.verdict, 'ai-disclosed');
});

test('code comment crediting an AI tool → ai-assisted', () => {
  const r = A.analyzeSite({ hostname: 'x', comments: [' This file was generated by GitHub Copilot '], bodyText: '' });
  assert.equal(r.verdict, 'ai-assisted');
});

test('visible "built with AI" statement → ai-disclosed', () => {
  const r = A.analyzeSite({ hostname: 'x', bodyText: 'Welcome! This website was built with AI in an afternoon.' });
  assert.equal(r.verdict, 'ai-disclosed');
});

test('conventional builder → builder verdict with placeholder trust notes', () => {
  const r = A.analyzeSite({ hostname: 'x', metas: [{ name: 'generator', content: 'Framer 1.0' }], bodyText: 'Call (555) 123-4567 or write to info@yourcompany.com. Lorem ipsum dolor sit amet.' });
  assert.equal(r.verdict, 'builder');
  assert.ok(r.trustNotes.length >= 3);
});

test('nothing → no-signal', () => {
  const r = A.analyzeSite({ hostname: 'x', bodyText: 'Hello world' });
  assert.equal(r.verdict, 'no-signal');
  assert.equal(r.signals.length, 0);
});
