const test = require('node:test');
const assert = require('node:assert/strict');
const T = require('../lib/text-analyzer.js');

const AI_PROSE = `In today's fast-paced digital landscape, businesses must navigate the complexities of an ever-evolving market. It is important to note that leveraging cutting-edge technology is paramount. Moreover, a robust strategy serves as a testament to resilience. Furthermore, companies that embark on this journey unlock the true potential of their teams. Ultimately, the tapestry of innovation is multifaceted, and it is worth noting that seamless integration fosters a vibrant culture. In conclusion, let's dive into the key takeaways: delve deeper, harness the power of data, and elevate your brand. Additionally, stakeholders should underscore the pivotal role of holistic planning. Whether you're a startup or an enterprise, this comprehensive guide will streamline your growth.`;

const HUMAN_PROSE = `I got to the shop late. Rain again, and the bus driver had that look. Anyway, the bread was gone, so I bought rolls, which my kid hates. We argued. Then we laughed about it because honestly who fights about rolls? Dinner was fine. I fell asleep on the sofa at nine with the telly on and woke up at two with a stiff neck. Tomorrow is the dentist. Not looking forward to that one bit, but it has to be done, and Sam said she would drive me, which helps.`;

test('LLM-flavoured prose scores as likely AI (heuristic only)', () => {
  const r = T.analyzeText(AI_PROSE);
  assert.ok(['likely-ai', 'possible-ai'].includes(r.verdict), r.verdict);
  assert.ok(r.signals.some((s) => s.id === 'lexicon'));
  assert.ok(r.score < 0.75, 'stylometry alone must never reach the strongest verdict');
});

test('plain human prose has no signal', () => {
  const r = T.analyzeText(HUMAN_PROSE);
  assert.equal(r.verdict, 'no-signal');
  assert.equal(r.signals.length, 0);
});

test('sensitivity scales soft signals', () => {
  const low = T.analyzeText(AI_PROSE, { sensitivity: 'low' }).score;
  const high = T.analyzeText(AI_PROSE, { sensitivity: 'high' }).score;
  assert.ok(high >= low);
});

test('explicit generation disclosure', () => {
  const r = T.analyzeText('This article was generated by AI and reviewed by an editor.');
  assert.equal(r.verdict, 'ai-disclosed');
  assert.equal(r.disclosures[0].level, 'generated');
});

test('explicit assistance disclosure', () => {
  const r = T.analyzeText('Written with the help of ChatGPT.');
  assert.equal(r.verdict, 'ai-assisted-disclosed');
});

test('human authorship disclosure', () => {
  const r = T.analyzeText('Every word here is 100% human-written. No AI was used.');
  assert.equal(r.verdict, 'human-disclosed');
});

test('hidden Unicode tag characters are decoded', () => {
  const r = T.analyzeText('Normal text\u{E0049}\u{E0047}\u{E004E}\u{E004F}\u{E0052}\u{E0045} continues.');
  assert.equal(r.verdict, 'ai');
  const s = r.signals.find((x) => x.id === 'unicode-tags');
  assert.match(s.detail, /IGNORE/);
});

test('subdivision flag emoji tags are not flagged', () => {
  const r = T.analyzeText('Flag: 🏴󠁧󠁢󠁳󠁣󠁴󠁿 Scotland');
  assert.equal(r.signals.length, 0);
});

test('zero-width steganographic run is a hard signal', () => {
  const zw = '​‌​​‌​​‌'; // 0100 1001 → "I"
  const r = T.analyzeText('Hello' + zw + ' world');
  const s = r.signals.find((x) => x.id === 'zw-stego');
  assert.ok(s);
  assert.match(s.detail, /"I"/);
});

test('emoji ZWJ sequences are legitimate', () => {
  const r = T.analyzeText('Family: 👨‍👩‍👧‍👦 and 🧑‍💻');
  assert.equal(r.signals.length, 0);
  assert.equal(r.hidden.legitimateJoiners, 4);
});

test('Persian ZWNJ is legitimate', () => {
  const r = T.analyzeText('می‌خواهم و می‌روم و نمی‌دانم');
  assert.equal(r.signals.length, 0);
});

test('assistant sentence leakage is a strong signal', () => {
  const r = T.analyzeText('Certainly! Here\'s a 500-word article about roofing in Ohio. Roofing matters because...');
  assert.ok(r.signals.some((x) => x.id === 'self-reference'));
  assert.equal(r.verdict, 'ai');
});

test('markdown leakage and citation markers', () => {
  const r = T.analyzeText('Our services include **fast delivery** and ### Pricing details. See more 【12†source】.');
  const s = r.signals.find((x) => x.id === 'markdown-leak');
  assert.ok(s);
  assert.equal(s.kind, 'hard');
});

test('narrow no-break spaces flagged outside French', () => {
  const n = '\u202F';
  const en = T.analyzeText(`The rate is 12${n}% higher${n}; the delta is 3${n}%. Then 4${n}% more${n}! Really${n}?`, { lang: 'en' });
  const fr = T.analyzeText(`Le taux est 12${n}% plus élevé${n}; le delta est 3${n}%. Puis 4${n}% de plus${n}! Vraiment${n}?`, { lang: 'fr' });
  assert.ok(en.signals.some((x) => x.id === 'narrow-nbsp'));
  assert.ok(!fr.signals.some((x) => x.id === 'narrow-nbsp'));
});

test('empty input', () => {
  assert.equal(T.analyzeText('').verdict, 'no-signal');
  assert.equal(T.analyzeText(null).verdict, 'no-signal');
});
