/*
 * lib/platform-labels.js — AI labels applied by the platform itself.
 *
 * Instagram, Facebook, TikTok, YouTube, LinkedIn and Pinterest strip embedded
 * metadata on upload, then re-add their own visible marker when their systems
 * (or the uploader) say the media is AI-made. Those markers are the only
 * provenance left on the page, so they are worth reading.
 *
 * Matching is by visible text and accessible name rather than by CSS class,
 * because platform class names are obfuscated and rotate constantly. Each
 * label is attributed to the nearest media element in the same post.
 */
(function (root, factory) {
  const api = factory(root);
  if (typeof module === 'object' && module.exports) module.exports = api;
  root.SRL = root.SRL || {};
  root.SRL.platformLabels = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';

  /* level: 'generated' — platform says the media is AI-made;
   *        'assisted'  — AI was used in part;
   *        'info'      — a provenance affordance with no verdict of its own. */
  const PLATFORMS = [
    {
      id: 'meta', name: 'Instagram / Facebook / Threads',
      hosts: /(^|\.)(?:instagram|facebook|threads|fb)\.(?:com|net)$/i,
      labels: [
        { re: /^\s*(?:made|imagined|created)\s+with\s+ai\s*$/i, level: 'generated', note: 'Meta applies this when the uploader declares AI or its detection finds industry-standard AI signals.' },
        { re: /^\s*ai\s+info\s*$/i, level: 'info', note: 'Meta shows "AI info" where content credentials or a declaration were detected; open it for what Meta found.' },
        { re: /ai[- ]generated\s+content/i, level: 'generated', note: 'Meta AI-generated content label.' },
      ],
    },
    {
      id: 'tiktok', name: 'TikTok',
      hosts: /(^|\.)tiktok\.com$/i,
      labels: [
        { re: /creator\s+labell?ed\s+as\s+ai[- ]generated/i, level: 'generated', note: 'Uploader declared the content as AI-generated.' },
        { re: /^\s*ai[- ]generated\s*$/i, level: 'generated', note: 'TikTok AI-generated label, applied by the uploader or by detected Content Credentials.' },
      ],
    },
    {
      id: 'youtube', name: 'YouTube',
      hosts: /(^|\.)(?:youtube\.com|youtu\.be)$/i,
      labels: [
        { re: /altered\s+or\s+synthetic\s+content/i, level: 'generated', note: 'YouTube requires creators to disclose realistic altered or synthetic content; this is that disclosure.' },
        { re: /sound\/?video\s+(?:is\s+)?altered\s+or\s+synthetic/i, level: 'generated', note: 'YouTube altered-or-synthetic disclosure.' },
        { re: /how\s+this\s+content\s+was\s+made/i, level: 'info', note: 'YouTube provenance panel; open it for the creator’s disclosure.' },
      ],
    },
    {
      id: 'linkedin', name: 'LinkedIn',
      hosts: /(^|\.)linkedin\.com$/i,
      labels: [
        { re: /^\s*(?:cr|content\s+credentials)\s*$/i, level: 'info', note: 'LinkedIn shows a Content Credentials marker when C2PA metadata survived upload.' },
        { re: /generated\s+with\s+ai/i, level: 'generated', note: 'LinkedIn AI-generation marker.' },
      ],
    },
    {
      id: 'pinterest', name: 'Pinterest',
      hosts: /(^|\.)pinterest\.[a-z.]{2,6}$/i,
      labels: [
        { re: /^\s*ai\s+modified\s*$/i, level: 'assisted', note: 'Pinterest labels Pins its systems judge to be AI-modified.' },
        { re: /generated\s+with\s+ai/i, level: 'generated', note: 'Pinterest AI-generation marker.' },
      ],
    },
    {
      id: 'x', name: 'X',
      hosts: /(^|\.)(?:x\.com|twitter\.com)$/i,
      labels: [
        { re: /^\s*made\s+with\s+grok\s*$/i, level: 'generated', note: 'Image generated by Grok inside X.' },
      ],
    },
  ];

  const MAX_LABEL_TEXT = 60;

  function platformFor(hostname) {
    /* No trailing dot: "www.tiktok.com." is the same host as
     * "www.tiktok.com" and has to match the same platform. */
    const h = String(hostname || '').toLowerCase().replace(/\.+$/, '');
    return PLATFORMS.find((p) => p.hosts.test(h)) || null;
  }

  /* Reads the accessible-ish name of a node: its own text, aria-label, title
   * or alt. Own text only, so a whole post body is never mistaken for a chip. */
  function labelText(node) {
    const aria = node.getAttribute && (node.getAttribute('aria-label') || node.getAttribute('title'));
    if (aria && aria.length <= MAX_LABEL_TEXT) return aria.trim();
    let own = '';
    for (const c of node.childNodes) if (c.nodeType === 3) own += c.nodeValue;
    own = own.trim();
    return own.length && own.length <= MAX_LABEL_TEXT ? own : '';
  }

  /* Finds the media the label belongs to: the largest image or video inside
   * the nearest article/post container, else the nearest media sibling. */
  function mediaFor(node, doc) {
    let scope = node;
    for (let i = 0; i < 8 && scope; i++) {
      if (scope.matches && scope.matches('article, [role="article"], [data-testid="tweet"], ytd-watch-flexy, ytd-video-renderer')) break;
      scope = scope.parentElement;
    }
    scope = scope || node.parentElement;
    if (!scope) return null;
    let best = null;
    let bestArea = 0;
    for (const m of scope.querySelectorAll('img, video, canvas')) {
      const r = m.getBoundingClientRect();
      const area = r.width * r.height;
      if (area > bestArea) { bestArea = area; best = m; }
    }
    return bestArea >= 4096 ? best : null;
  }

  /*
   * Scans a document for platform AI labels.
   * `doc` and `scan` are injected so this is testable without a browser.
   * Returns [{ platform, level, text, note, media }].
   */
  function scanLabels(hostname, doc, opts = {}) {
    const platform = platformFor(hostname);
    if (!platform || !doc || !doc.querySelectorAll) return [];
    const max = opts.max || 40;
    const out = [];
    const seen = new Set();
    const candidates = doc.querySelectorAll('span, div, a, button, [aria-label], [title], figcaption');
    let checked = 0;
    for (const node of candidates) {
      if (out.length >= max || checked++ > 6000) break;
      const text = labelText(node);
      if (!text) continue;
      for (const l of platform.labels) {
        if (!l.re.test(text)) continue;
        const media = opts.skipMedia ? null : mediaFor(node, doc);
        const key = (media ? (media.currentSrc || media.src || '') : '') + '|' + text.toLowerCase();
        if (seen.has(key)) break;
        seen.add(key);
        out.push({ platform: platform.name, platformId: platform.id, level: l.level, text, note: l.note, media });
        break;
      }
    }
    return out;
  }

  /* Converts a label into the image-signal shape used by verdicts.js. */
  function toImageSignal(label) {
    const verdict = label.level === 'generated' ? 'ai-disclosed' : label.level === 'assisted' ? 'ai-disclosed' : 'no-signal';
    return {
      id: 'platform-label',
      hard: false,
      verdict,
      strength: label.level === 'generated' ? 0.9 : label.level === 'assisted' ? 0.7 : 0,
      label: label.level === 'info' ? label.platform + ' shows a provenance marker' : label.platform + ' labels this as ' + (label.level === 'generated' ? 'AI-generated' : 'AI-modified'),
      detail: '“' + label.text + '”. ' + label.note,
    };
  }

  return { PLATFORMS, platformFor, scanLabels, toImageSignal, labelText, mediaFor };
});
